#!/usr/bin/env python3
import requests, json, subprocess

# http://worldtimeapi.org/api/ip
# MMDDhhmmYYYY

raw_data = requests.get("http://worldtimeapi.org/api/ip").text
data = json.loads(raw_data)

datetime = data["datetime"]

day = ""
minute = ""
hour = ""
month = ""
year = ""
counter = 0

# Extracting time from the JSON
for x in datetime:

    if counter in [0, 1, 2, 3]:
        year += x

    if counter in [5, 6]:
        month += x

    if counter in [8, 9]:
        day += x

    if counter in [11, 12]:
        hour += x

    if counter in [14, 15]:
        minute += x

    counter += 1

combined = month + day + hour + minute + year

print(f"Date in DD/MM/YYYY hour:minute \nTime: {day}/{month}/{year} {hour}:{minute}")
confirm = input("Do you want to keep this time? [Y/n]: ")

if confirm in ["", "  ", "Y", "y", "Yes", "yes"]:
    subprocess.run(["sudo", "date", combined])

else:
    print("Exiting...")
    quit()
