#!/usr/bin/env python3
import requests, json 
from subprocess import PIPE, run

# http://worldtimeapi.org/api/ip
# MMDDhhmmYYYYi

def httperror_assess(e):

    if e in [x for x in range(400, 499)]:
        print(f"Client Error {e}. Please try again later.")
                            
    elif e in [x for x in range(500, 599)]:
        print(f"Server Error {e}. Please try again later.")
                                            
    else:
        print(f"An error occured with status number of {e}")

try:
    raw_data = requests.get("http://worldtimeapi.org/api/ip").text
    data = json.loads(raw_data)

except HTTPError as e:
    httperror_assess(e.code)

datetime = data["datetime"]

# Extracting time from the JSON
year = ''.join(datetime[0:4])
month = ''.join(datetime[5:7])
day = ''.join(datetime[8:10])
hour = ''.join(datetime[11:13])
minute = ''.join(datetime[14:16])

combined = month + day + hour + minute + year

current_time = run(["date", "+'%d/%m/%Y %R'"], stdout=PIPE, stderr=PIPE, universal_newlines=True)
current_time = (current_time.stdout).replace("'", "")

print(f"""
Date in DD/MM/YYYY hour:minute
------------------------------
Your time:    {current_time}Updated time: {day}/{month}/{year} {hour}:{minute} 
------------------------------""")

confirm = input("Do you want to keep the updated time? [Y/n]: ")

if confirm in ("", "  ", "Y", "y", "Yes", "yes"):
    run(["sudo", "date", combined])

else:
    print("Exiting...")
    raise SystemExit()
